### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by mweststrate** [foxhound87/rfx-stack#1]
Hey!

So far I still failed to get the server up & running reliably. First of all, there seems to be some missing deps, I needed to add the following:

``` diff
+    "babel-plugin-transform-decorators": "^6.6.5",
+    "serve-static": "^1.10.2",
```

After that I get errors on the `build:server` task: 

```
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/styles/app.bar.mdl.css
Module build failed: Error: ENOENT: no such file or directory, open '/home/michel/mobservable/rfx-stack/src/styles/_basscss-padding.css'
    at Error (native)
 @ ./src/styles/app.bar.mdl.css 2:18-207

ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/styles/app.nav.mdl.css
Module build failed: Error: ENOENT: no such file or directory, open '/home/michel/mobservable/rfx-stack/src/styles/_basscss-layout.css'
    at Error (native)
 @ ./src/styles/app.nav.mdl.css 2:18-207

ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/_global.css
Module build failed: Error: ENOENT: no such file or directory, open '/home/michel/mobservable/rfx-stack/src/styles/_basscss-hide.css'
    at Error (native)
 @ ./src/styles/_global.css 2:18-130
```

And similar ones on the `build:client`task:

```
> react-kickstart@1.0.0 build:client /home/michel/mobservable/rfx-stack
> npm run clean:client && NODE_ENV=production webpack -p --progress


> react-kickstart@1.0.0 clean:client /home/michel/mobservable/rfx-stack
> rimraf ./public/build

 69% 601/604 build modulesModuleBuildError: Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open '/home/michel/mobservable/rfx-stack/src/styles/_basscss-padding.css'
    at Error (native)
    at DependenciesBlock.onModuleBuildFailed (/home/michel/mobservable/rfx-stack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/michel/mobservable/rfx-stack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/michel/mobservable/rfx-stack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
```

So I'm guessing I miss some files or I don't have the correct versions of some dependencies, my npm ls output is:

```
➜  rfx-stack git:(master) ✗ npm ls --depth=0
react-kickstart@1.0.0 /home/michel/mobservable/rfx-stack
├── animate.css@3.5.1
├── autoprefixer@6.3.4
├── babel-core@6.5.2
├── babel-eslint@5.0.0
├── babel-loader@6.2.4
├── babel-plugin-transform-class-properties@6.6.0
├── babel-plugin-transform-decorators@6.6.5
├── babel-plugin-transform-decorators-legacy@1.3.4
├── babel-plugin-transform-runtime@6.6.0
├── babel-polyfill@6.5.0
├── babel-preset-es2015@6.5.0
├── babel-preset-react@6.5.0
├── babel-preset-react-hmre@1.1.1
├── babel-preset-stage-0@6.5.0
├── babel-root-import@3.1.0
├── basscss@8.0.1
├── basscss-btn@1.1.1
├── basscss-positions@1.0.5
├── basscss-responsive-states@1.0.6
├── basscss-ui-utility-groups@1.0.1
├── better-npm-run@0.0.8
├── bluebird@3.3.4
├── body-parser@1.15.0
├── classnames@2.2.3
├── compression@1.6.1
├── connect-history-api-fallback@1.1.0
├── cors@2.7.1
├── css-loader@0.23.1
├── css-modules-require-hook@4.0.0
├── cssnano@3.5.2
├── dotenv@2.0.0
├── ejs@2.4.1
├── eslint@1.10.3
├── eslint-config-airbnb@5.0.1
├── eslint-loader@1.3.0
├── eslint-plugin-jsx-control-statements@1.1.0
├── eslint-plugin-react@3.16.1
├── exports-loader@0.6.3
├── extract-text-webpack-plugin@1.0.1
├── faker@3.0.1
├── feathers@2.0.0
├── feathers-hooks@1.5.0
├── feathers-query-filters@1.5.1
├── feathers-rest@1.2.4
├── feathers-socketio@1.3.3
├── feathers-waterline@1.1.0
├── getenv@0.6.0
├── globule@0.2.0
├── imports-loader@0.6.5
├── isdev@1.0.1
├── isomorphic-fetch@2.2.1
├── isomorphic-style-loader@0.0.12
├── json-loader@0.5.4
├── json-stringify-safe@5.0.1
├── jsx-control-statements@3.1.0
├── lodash@4.4.0
├── match-media@0.2.0
├── material-ui@0.15.0-alpha.2
├── mobx@2.0.4
├── mobx-react@3.0.3
├── mobx-react-devtools@4.0.2
├── moment@2.11.2
├── morgan@1.7.0
├── node-uuid@1.4.7
├── normalize.css@3.0.3
├── npm-install-webpack-plugin@2.0.2
├── postcss@5.0.19
├── postcss-import@8.0.2
├── postcss-loader@0.8.2
├── precss@1.4.0
├── pretty-error@2.0.0
├── react@0.14.7
├── react-css-modules@3.7.6
├── react-dom@0.14.7
├── react-router@2.0.1
├── react-sticky@4.0.1
├── react-tap-event-plugin@0.2.2
├── rimraf@2.5.2
├── rss-watcher@1.3.0
├── sails-mongo@0.12.0
├── serve-static@1.10.2
├── socket.io-client@1.4.5
├── style-loader@0.13.1
├── waterline@0.11.2
├── webpack@1.12.14
├── webpack-dev-middleware@1.5.1
├── webpack-hot-middleware@2.7.1
├── webpack-merge@0.7.3
├── whatwg-fetch@0.11.0
└── winston@2.2.0
```

Hope that helps! I'm really curious to try this out :)

**Comment by foxhound87** [comment]
I updated the project with the two dependencies you need.
I checked your dependencies and are ok, except my style-loader is @0.13.0.
It's curious that the style loader want to load a file that doesn't exist.
It seems related to basscss imports, the loader treats those as local files, but postcss-import should load them globally from the related npm package. I have to investigate why it has this behavior.

**Comment by foxhound87** [comment]
I removed all import/extend from the css modules; In the meantime I'll find a better solution to use global class inside a module. So now you should setup the project without errors.
