### ISSUE TITLE
Cannot find module './_baseClone' running api:dev

### ISSUE THREAD

**Issue by slikts** [foxhound87/rfx-stack#19]
```
Error: Cannot find module './_baseClone'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/slikts/rfx-stack/node_modules/babel-core/node_modules/babel-register/node_modules/lodash/cloneDeep.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

OS: Debian 8
Node: v6.2.2

**Comment by foxhound87** [comment]
It seems a babel-core / babel-register issue related at lodash.
What npm/node version are you using?
Make sure you are using at least node v5 and npm v3.3

**Comment by slikts** [comment]
I have Node 6.2.2 and npm 3.9.5. I cloned this repo and ran `npm install`.

**Comment by foxhound87** [comment]
Yah I read it now, sorry.

I don't know why you get this error, I have to deepen more.
You can try to remove `_.cloneDeep()` from the modal styling. You can find it on these files:
https://github.com/foxhound87/rfx-stack/search?utf8=%E2%9C%93&q=_.cloneDeep
But I'm not sure if it's related to those lines.

**Comment by foxhound87** [comment]
But definitely can't be related to those lines, are not called by the api server.
I'm installing debian 8 to reproduce your issue.

**Comment by foxhound87** [comment]
Tested on a fresh install of Debian 8.5 using node v6.2.2 (npm v3.9.5). All working. 
Since your issue seems to occur only on your particular system environment, I consider this issue as closed.

I will reopen it if you can provide me more details.
