### ISSUE TITLE
npm run seed:dev - Seeding Error. 

### ISSUE THREAD

**Issue by jonandrewdavis** [foxhound87/rfx-stack#30]
Hey man. Great work on this stack.  👍 

Curious though, if you could tell me something about this issue:

When:
`npm run seed:dev`

Get:

```
> rfx-stack@0.7.0-alpha.7 seed:dev /Users/zjh266/Desktop/rfx-stack
> cross-env NODE_ENV=development node ./run/start.seeder.js

/Users/zjh266/Desktop/rfx-stack/src/utils/logger.js:1
(function (exports, require, module, __filename, __dirname) { import log from 'winston';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/zjh266/Desktop/rfx-stack/run/init.js:5:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/zjh266/.nvm/versions/node/v5.8.0/bin/node" "/Users/zjh266/.nvm/versions/node/v5.8.0/bin/npm" "run" "seed:dev"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! rfx-stack@0.7.0-alpha.7 seed:dev: `cross-env NODE_ENV=development node ./run/start.seeder.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rfx-stack@0.7.0-alpha.7 seed:dev script 'cross-env NODE_ENV=development node ./run/start.seeder.js'.
```

Looks to me that this isn't babel-fying properly or something?
If I run babel-node on this proceess it actually works fine, but then the globals from the `.env` aren't detected and it errors in `shared/app.js`

Again, great work here, thanks for any solutions you can spot.

**Comment by foxhound87** [comment]
This issue is due to the recent webpack 2 config upgrade.

Should be fixed now: https://github.com/foxhound87/rfx-stack/commit/b71cdeeade5d6c1df93ec654112ce04e0904c598

**Comment by jonandrewdavis** [comment]
Thank you. This fixed the issue.

**Comment by JJMoon** [comment]
Hello. I am newbie to Feathersjs. I forked this repo, and set mongodb, npm run api:dev.
But, I got similar error as follows when I run seed:dev
```

> rfx-stack@0.8.0-alpha.8 seed:dev /Volumes/Data/StudyPrjt/rfx-stack
> cross-env NODE_ENV=development node ./run/start.seeder.js

info:    --- Seed Error ---------------------------
info:    ------------------------------------------
{ NotAuthenticated: No auth token
    at NotAuthenticated.ExtendableBuiltin (/Volumes/Data/StudyPrjt/rfx-stack/node_modules/feathers-errors/lib/index.js:21:28)
    at NotAuthenticated.FeathersError (/Volumes/Data/StudyPrjt/rfx-stack/node_modules/feathers-errors/lib/index.js:96:116)
    at new NotAuthenticated (/Volumes/Data/StudyPrjt/rfx-stack/node_modules/feathers-errors/lib/index.js:149:117)
    at /Volumes/Data/StudyPrjt/rfx-stack/node_modules/feathers-authentication/lib/hooks/authenticate.js:79:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
  type: 'FeathersError',
  name: 'NotAuthenticated',
  code: 401,
  className: 'not-authenticated',
  data: {},
  errors: {} }
```
