### ISSUE TITLE
map is not a function

### ISSUE THREAD

**Issue by richieio** [foxhound87/rfx-stack#39]
Hi Claudio,

I'm having trouble running `npm run web:dev` with the latest rfx-stack. Seems something wrong with mobx-react-form, but I can't figure out what's the problem. Here is the full error.

```
/home/rich/dev/rfx-stack/node_modules/mobx-react-form/lib/Form.js:256
    return _mobx.observable.map({}) || (0, _mobx.asMap)({});
                            ^

TypeError: _mobx.observable.map is not a function
    at AuthForm.initializer (/home/rich/dev/rfx-stack/node_modules/mobx-react-form/lib/Form.js:256:29)
    at /home/rich/dev/rfx-stack/node_modules/mobx/lib/mobx.js:2573:76
    at /home/rich/dev/rfx-stack/node_modules/mobx/lib/mobx.js:2612:122
    at Array.forEach (native)
    at runLazyInitializers (/home/rich/dev/rfx-stack/node_modules/mobx/lib/mobx.js:2612:82)
    at AuthForm.get [as fields] (/home/rich/dev/rfx-stack/node_modules/mobx/lib/mobx.js:2579:25)
    at AuthForm.select (/home/rich/dev/rfx-stack/node_modules/mobx-react-form/lib/shared/Utils.js:56:54)
    at /home/rich/dev/rfx-stack/node_modules/mobx-react-form/lib/shared/Initializer.js:86:41
    at /home/rich/dev/rfx-stack/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/home/rich/dev/rfx-stack/node_modules/lodash/_baseForOwn.js:13:20)
```

**Comment by foxhound87** [comment]
Sorry for this issue, `observable.map`  is introduced for mobx 3 support.

This release will fix the issue: 

https://github.com/foxhound87/mobx-react-form/releases/tag/v1.18.4

Thank You

**Comment by richieio** [comment]
Thanks! It works! Much appreciated.
